#!/bin/bash
# Clean out all autogenerated files in this directory.
rm -f amppackager_cert_consumer.yaml
rm -f amppackager_cert_renewer.yaml
rm -f amppkg_consumer.toml
rm -f amppkg_renewer.toml
rm -f amppkg.privkey
rm -f amppkg.csr
rm -f san.cnf

