apiVersion: apps/v1 
kind: Deployment
metadata:
  name: amppackager-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: amppackager-nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-renewer-pvc
      volumes:
        - name: nfs-renewer-pvc
          gcePersistentDisk:
            pdName: amppackager-nfs-disk
            fsType: ext4
