#!/bin/bash

# AMPPackager requires that you have 2 items so that auto-renewal of
# certificates work:
# - Certificate Signing Request (CSR)
# - Private key
# This can be autogenerated for you by the ./gcloud_up.sh script or you
# can manually create these by following the instructions in this link:
# https://docs.digicert.com/manage-certificates/certificate-profile-options/get-your-signed-http-exchange-certificate/
# If you manually generate these files, make sure to use the filenames that you
# specified below (e.g. AMP_PACKAGER_CSR_FILENAME value should be the name used for
# the CSR file).

# GCloud project information
# REQUIRED
export PROJECT_ID="amp-packager-on-gcloud-test"
export COMPUTE_ENGINE_ZONE="us-west1-a"

# The version tag of the docker build of amppackager you want to build/use.
# You can leave it as the default unless you want to use a specific version
# of amppackager.
# OPTIONAL
export AMP_PACKAGER_VERSION_TAG="latest"

# The number of amppackager consumer replicas you'd like to run to which the
# load balancer can forward requests.
export AMP_PACKAGER_NUM_REPLICAS=2

# The domain you want to use for the signed exchange.
# REQUIRED
export AMP_PACKAGER_DOMAIN="azei-package-test.com"
export AMP_PACKAGER_COUNTRY="US"
export AMP_PACKAGER_STATE="California"
export AMP_PACKAGER_LOCALITY="San Jose"
export AMP_PACKAGER_ORGANIZATION="Greg Grothaus"

# ACME API related information
# REQUIRED
export ACME_EMAIL_ADDRESS="banaag@google.com"
export ACME_DIRECTORY_URL="https://acme.digicert.com/v2/acme/directory/q-L_oMUirCjCLx2HXXz8eSRjUqfqsRSCfnVlySntl8E"

# The Signed Exchange Certificate you got from your certificate authority
# (Digicert) using the domain/location information above.
# OPTIONAL (if file is not present, amppackager renewer instance will try to
# retrieve one for you).
# DO NOT CHECK IN INTO GITHUB.
export AMP_PACKAGER_CERT_FILENAME="amppkg.cert"

# These files can be autogenerated.  You can choose replace it with your own
# file if desired but each file has to be present in your
# local amppackager/deploy/gcloud directory.
# OPTIONAL (if files are not present, script will autogenerate them for you)
# DO NOT CHECK THEM INTO GITHUB.
export AMP_PACKAGER_CSR_FILENAME="amppkg.csr"
export AMP_PACKAGER_PRIV_KEY_FILENAME="amppkg.privkey"

